### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Tourniercy** [Tourniercy/RunningApp#2]
- [ ] Circle start end
- [ ] Animation switch screen
- [ ] Calcul vitesse moyenne, actuel et maximum
